### PR TITLE
Restore the trust store for Anvil SSL cert.

### LINKED ISSUE #651: [BUG] SSL error when Promotion manager connecting to Anvil server
**Describe the bug**
When the promotion manager tries to connect to the server, the following error is thrown:
```
javax.net.ssl.SSLException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
	at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:133)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:325)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:268)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:263)
	at java.base/sun.security.ssl.SSLSocketImpl.handleException(SSLSocketImpl.java:1654)
```
The app cannot connect to the server, and the feature is broken.

This seems to be caused by 919b2abc46c5be317cafc12d1b999b497b99a49f which removed the trust store holding the Anvil TLS cert chain

**To Reproduce**
1. Go to League Details
2. Observe the promotion details message: "Your current promotion/demotion status is unknown..." all the time
3. Look at the logs

**Screenshots**
N/A

**Platform information:**
 - OS: MacOS
 - Version master

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by tychobrailleur**
This also renames the JKS file as I must have not been awake when I
originally named it.  This fixes #651.

1. changes proposed in this pull request:
 
   - fixes issue #651 
   
   - if not fixing an existing issue, comments explaining the purpose of the PR should be provided)
 
 
2. changelog and release_notes ...

 - [ ] have been updated
 - [x] do not require update

3. [Optional] suggested person to review this PR @akasolace

### CODE REVIEW

**Comment by akasolace** [comment]
does the file src/main/resources/truststore.jks  need to be copied somewhere during the packaging phase? I am not sure if some changes are also required on install4j side ...

**Comment by akasolace** [comment]
@tychobrailleur just to ping https://github.com/akasolace/HO/pull/652#issuecomment-674746262

**Comment by tychobrailleur** [comment]
I have just tested on the macOS app you have packaged, and it is indeed failing, so the jks file must be missing from the distribution.  I will look into that, and amend this PR accordingly!

**Comment by tychobrailleur** [comment]
> I have just tested on the macOS app you have packaged, and it is indeed failing, so the jks file must be missing from the distribution. I will look into that, and amend this PR accordingly!

Follow up on this: I have just tested with a packaged built off this PR, and the jks is included, and the promotion feature works as expected.   So this PR can be merged, and should be enough.

**Pull request merged**
