### PR TITLE
Solve issue with image loading in darklaf.

### PR DESCRIPTION
**Pull request by tychobrailleur**
1. changes proposed in this pull request:
 
Explicitly retrieve image when darklaf is used, as image only gets loaded after interacting with UI.
 
 
2. changelog and release_notes ...

 - [ ] have been updated
 - [x] do not require update

3. [Optional] suggested person to review this PR @akasolace

### CODE REVIEW

**Comment by akasolace** [comment]
@tychobrailleur is this only a bug in darklaf ? I am not sure but I thought I experienced the same behaviour in Nimbus ...

**Comment by tychobrailleur** [comment]
I could not reproduce on Nimbus, it only seemed to happen on darklaf themes for me.

**Comment by akasolace** [comment]
> I could not reproduce on Nimbus, it only seemed to happen on darklaf themes for me.

ok

@weisJ  I cc you to keep you informed of that issue

**Comment by tychobrailleur** [comment]
Did it fix the issue for you, @akasolace ?

**Comment by akasolace** [comment]
@tychobrailleur tbh, I did not try it yet. I will do that as soon as I rebase my branch (today or tomorrow) ....

**Comment by akasolace** [comment]
@tychobrailleur so I tested it yesterday and it has been fixed in one place but not in the other. 
I will share animated gif this evening to make it clearer but the situation is that:
   - clock icon now appears correctly from the start
   - club logo: the default icon which is loaded by the problematic function, only appears after interaction (mouse hover)

**Comment by tychobrailleur** [comment]
> @tychobrailleur so I tested it yesterday and it has been fixed in one place but not in the other.

Ah, yes, I can imagine as I didn't look at the other one.  I'll amend the PR.

**Comment by weisJ** [comment]
This problem should be fixed in the darklaf `latest.intergration` version. Because darklaf uses caching and lazy evaluation for derived images (i.e. they are only loaded when needed and share the same original image for optimal quality) sometimes the images could not be available when painting as AWT loads images asynchronously.

**Comment by akasolace** [comment]
@weisJ ok good to know this will be fixed upstream. Meanwhile @tychobrailleur found a ix.

**Pull request merged**
