### PR TITLE
Display further last match info in squad table view

### PR DESCRIPTION
**Pull request by sophiastr**
1. changes proposed in this pull request:
 
   - fixes issue #1523  
   
   - if not fixing an existing issue, comments explaining the purpose of the PR should be provided)
 
 
2. changelog and release_notes ...

 - [ ] have been updated
 - [ ] do not require update

3. [Optional] suggested person to review this PR @wsbrenk 

Στιγμιότυπο οθόνης (705)

### CODE REVIEW

**Comment by sophiastr** [comment]
I think something is going wrong with squad table view(user column in PlayerOverviewModel class).
Some columns have double cells,  others disappear when I move them and others do not stay where I placed them. Have you seen this problem too?

**Review by wsbrenk — CHANGES_REQUESTED** [review]
sorry -  i forgot to submit this review

**Comment by sophiastr** [comment]
Hello @wsbrenk ,
I am facing a strange problem. Squad table view shows only 52 columns. After that, it doesn't display anything. Is there something I don't understand well? Is there another class that indicates how many columns will be printed? Moreover, the information about the last match date is stored at additionalArray at position 10. But we use this command: columns[22] = additionalArray[9]; to display that information. Finally, the information about the rating(not the lastratingendgame) doesn't appear in squad table view.

**Comment by wsbrenk** [comment]
@sophiastr did you check if your colums appears in File->PReferences->Columns ?

**Comment by sophiastr** [comment]
Hello @wsbrenk ,

Yes it appers. Please check my pull request. 
I would be very happy if I did what you wanted and if you accepted my Pull request
Thank you Sophia

**Pull request merged**
