### PR TITLE
Fix an error in personality translations

### PR DESCRIPTION
**Pull request by maurooaranda**
A friend of mine found this error: Personality translations in spanish are inverted.
Agreeability and honesty are mixed, so the display in the player info is inaccurate.

 I don't develop in Java, so I'm really not sure this fixes the problem, but it will be easy for some dev to check it.

Best regards,
Mauro.

1. changes proposed in this pull request:
 
Personality attributes agreeability and honesty are inverted, so fix them.

2. changelog and release_notes ...

 - [ ] have been updated
 - [X] do not require update

I think this doesn't need an update.

### CODE REVIEW

**Comment by akasolace** [comment]
@maurooaranda  thank you for the PR but unfortunately, this is not how it can be fixed.

translations should be fixed using https://poeditor.com/join/project/jCaWGL1JCl  
maybe you or your friend can fix it there,  very appreciated !

**Comment by maurooaranda** [comment]
Ok, no problem.  I've already joined to the project in POeditor, but it told me I should wait for something like an approval.  So I'll wait for that and try to fix it there.

Thanks for taking over this project.

**Comment by akasolace** [comment]
@maurooaranda  you should be approved now ...

**Comment by maurooaranda** [comment]
Ok, thanks.  I've now made the change in POEditor.

**Comment by akasolace** [comment]
@maurooaranda  perfect thank you

**Pull request closed without merging**
