### PR TITLE
Issue#7

### PR DESCRIPTION
**Pull request by mistermax80**
Now on MacOS the shirt's number shows good, but I ask to @akasolace to try modify on windows system.
schermata 2018-12-09 alle 18 29 58

### CODE REVIEW

**Comment by akasolace** [comment]
@mistermax80 
Thank you for the new PR, 
if I understand your comment, you just want me to try this under windows, correct ?

**Comment by mistermax80** [comment]
Yes, do you try if work fine under Windows?
Else I Will manage the system platform.
Now the icon shirt and Number Is 30x14, After was 24×14.
I test on all screen It's showed.

**Comment by akasolace** [comment]
@mistermax80 

**before**  shirt were centered and font was normal  (clean display)
image

**with your commit**  shirt are not centered and font is bold (display still clean)
image

I guess this is is because I got plenty of players without a tshirt numbers. Do you know how to fix that ?
btw, where the colour of the shirt is coming from in your HO ? on mine they are all grey ?

I also remarked, that column has no title, maybe you can also name it -it would make a new entry in the **English translation files**.  No need to touch others are they are automatically generated.

Cheers.

**Comment by mistermax80** [comment]
> I guess this is is because I got plenty of players without a tshirt numbers. Do you know how to fix that ?
Yes, I think to know.
For bold font I didn't modify type... It's always bold, if you think is the better plain, I can modify it.

> btw, where the colour of the shirt is coming from in your HO ? on mine they are all grey ?
The colour of the shirt came from lineup set, black = goolkeeper...

> I also remarked, that column has no title, maybe you can also name it -it would make a new entry in the English translation files. No need to touch others are they are automatically generated.
Ok, I can do it

**Comment by akasolace** [comment]
> Yes, I think to know.
For bold font I didn't modify type... It's always bold, if you think is the better plain, I can modify it.

The bold was not recognized then because it was displayed plained (at least in Windows) 
I think I prefer to keep it plain otherwise it stand out too much compare to the rest

> The colour of the shirt came from lineup set, black = goolkeeper...

I am not sure I got it :-( , for some of my players I set the best position field in Squad tab, but still all shirts are grey ...

Thank you.

**Comment by mistermax80** [comment]
Ok, I made all!
The label name was not setting, but it was setting as tooltip, and I reused the tooltip language reference it was already present.
Removing the bold the dimension image is 28x14 (orig: 24x14, bold: 30x14)
Please, Could you try if in windows It's ok?

**Comment by akasolace** [comment]
@mistermax80 

ok great, I'll test it tonight.
Can't wait because I think to release 1.435 after closing that bug.

**Comment by akasolace** [comment]
Thank you

**Pull request merged**
