### PR TITLE
Show consolation cup in 3.x release

### PR DESCRIPTION
**Pull request by tychobrailleur**
Cherry-picked da4f3a4a9c7a1b4a2757c0793f6f0cea0c9bee75 to address issue #625 

1. changes proposed in this pull request:
 
   - fixes issue #625 
 
 
2. changelog and release_notes ...

 - [x] have been updated
 - [ ] do not require update

3. [Optional] suggested person to review this PR @yaute74

### CODE REVIEW

**Comment by akasolace** [comment]
@tychobrailleur  @yaute74  with the move to installed,  building artefacts for 3.x will be challenging ..... It is feasible but not sure I wan to invest a lot of time just to build a last 3.x .... I would rather stick to 4.0 release.  What do you think ?

**Comment by yaute74** [comment]
@akasolace as long as we don't have anything blocking, I think it's not necessary

**Comment by tychobrailleur** [comment]
> @tychobrailleur @yaute74 with the move to installed, building artefacts for 3.x will be challenging ..... It is feasible but not sure I wan to invest a lot of time just to build a last 3.x .... I would rather stick to 4.0 release. What do you think ?

I would also personally stick to 4.0 (that would also address the Linux distribution issues, I would think?), but I guess this depends on the release timeline.  I think we are still a fair bit away from being ready, so some of the of the 3.x issues may need an earlier release?

**Comment by akasolace** [comment]
> > @tychobrailleur @yaute74 with the move to installed, building artefacts for 3.x will be challenging ..... It is feasible but not sure I wan to invest a lot of time just to build a last 3.x .... I would rather stick to 4.0 release. What do you think ?
> 
> I would also personally stick to 4.0 (that would also address the Linux distribution issues, I would think?), but I guess this depends on the release timeline. I think we are still a fair bit away from being ready, so some of the of the 3.x issues may need an earlier release?

yes that was the point of the 3.x release branch but the swith to install4j makes it a bit heavy .... let see how things develop ...

**Pull request merged**
