### PR TITLE
#470 break up statistics on module matches

### PR DESCRIPTION
**Pull request by MaSedlacek**
1. changes proposed in this pull request:
 
   - fixes issue #470  
 
 
2. changelog and release_notes ...

 - [ ] have been updated
 - [ ] do not require update
 - [x] to be updated

Implementation of #470 + minor code cleanup.
Master in my fork was not the latest but seems there are no conflicts. Should you spot any, let me know and I'll rebase.

### CODE REVIEW

**Comment by MaSedlacek** [comment]
Forgot to mention - I don't have any neutral games with my team. Is there any test db I could use to test the feature? If not, please pay special attention to neutral games filter.

**Comment by akasolace** [comment]
Hello, 

Translation needs to be done through PoEditor, I am afraid you will loose the Czech translations ... 
Also should I expect another PR regarding release notes update ? 

Thank you for your first contribution on this long due feature ...

**Comment by MaSedlacek** [comment]
Sorry about the release notes, didn't find them in the project structure before. I added a line in a new pull request #1035.

As for the Czech translations, I may add them via PoEditor later. There were quite many untranslated strings so I guess it's ok if I don't (no clue how many people use Czech version, I use English)

**Comment by akasolace** [comment]
yes definitely ok, this is for translators ....

**Pull request merged**
