### PR TITLE
fix PlayerDataManager.getCurrentHTSeason /Week performance issue

### PR DESCRIPTION
**Pull request by wsbrenk**
1. changes proposed in this pull request:
 
   - fixes issue #1072, #1051
   
   - if not fixing an existing issue, comments explaining the purpose of the PR should be provided)
 
 
2. changelog and release_notes ...

 - [ ] have been updated
 - [x] do not require update

3. [Optional] suggested person to review this PR @___

### CODE REVIEW

**Comment by akasolace** [comment]
@wsbrenk  any idea how those corrupted entries arrived ? any side effects in deleting those entries ?

**Comment by wsbrenk** [comment]
@akasolace the methods getCurrentHtSeason/-week calculated giant numbers since february. had to do with UserParameter.instance().TimeZoneDifference changes.

**Comment by akasolace** [comment]
I thought there were method for this in the new date class, no ?

**Comment by wsbrenk** [comment]
for the purpose in ta_player table no TimeZoneDifference is required. a weeknumber was calculated to order the player information by date. this calculation weren't correct in all places - so i concentrated them in one place and made it correct - hopefully.

**Pull request merged**
