### PR TITLE
#477: removed MatchAnalyzer module

### PR DESCRIPTION
**Pull request by wsbrenk**
1. changes proposed in this pull request:
 
   - fixes issue #477
   
   - if not fixing an existing issue, comments explaining the purpose of the PR should be provided)
 
 
2. changelog and release_notes ...

 - [x] have been updated
 - [ ] do not require update

3. [Optional] suggested person to review this PR @___

### CODE REVIEW

**Comment by akasolace** [comment]
@wsbrenk have you try what this would give for someone having this module currently activated and upgrading to 3.0? Is there not something in the user preference database that should be fixed also ?

**Comment by wsbrenk** [comment]
@akasolace before applying the changes i activated match analyzer module. when invoking ho after the changes the module simply was gone. 
i checked if database tables exists for this module and didn't find any. i forgot the user configuration table. good point. i will check that and also the language strings could be cleaned if some of them were exclusivly used by the  match analyzer.

**Comment by akasolace** [comment]
>  i forgot the user configuration table. good point. i will check that and also the language strings could be cleaned if some of them were exclusivly used by the match analyzer.

@wsbrenk  ok great I wait your feedback on those 2 points before merging, cheers

**Comment by wsbrenk** [comment]
i did not find any exclusiv entries in database tables

**Comment by akasolace** [comment]
@wsbrenk last think is there not some icons that can also be removed, like home.png / away.png, ....
worst case we could clean this later on if you don't want to look at it now. As I guess @tychobrailleur will have a clear view of the used/unused icons while working on the new themes

**Comment by wsbrenk** [comment]
i'll check that

**Comment by wsbrenk** [comment]
@akasolace @tychobrailleur  found 2 icons exclusively used by the match analyzer

**Pull request merged**
