### PR TITLE
#623 rebased

### PR DESCRIPTION
**Pull request by wsbrenk**
1. changes proposed in this pull request:
 
   - fixes issue #623: Walkover specific training minutes were examined in MatchStatistics class
   
   - if not fixing an existing issue, comments explaining the purpose of the PR should be provided)
 
 
2. changelog and release_notes ...

 - [x] have been updated
 - [ ] do not require update

3. [Optional] suggested person to review this PR
especially @yaute74 should have a look on this request. i think he was working on training calcs in the past. i hope he agrees the move of calculation from HOModel to TrainingManager.

### CODE REVIEW

**Comment by akasolace** [comment]
@yaute74 do you think you can review this PR soon?

**Comment by akasolace** [comment]
@wsbrenk we can close this one and only merge #640 right ?

**Comment by wsbrenk** [comment]
> 
> 
> @wsbrenk we can close this one and only merge #640 right ?

yes

**Comment by akasolace** [comment]
included in #640

**Pull request closed without merging**
