### PR TITLE
#960 training download

### PR DESCRIPTION
**Pull request by wsbrenk**
1. changes proposed in this pull request:
 
   - fixes issue #960 (alternative approach)

Future training is updated too

2. changelog and release_notes ...

 - [ ] have been updated
 - [x] do not require update

3. [Optional] suggested person to review this PR @akasolace

### CODE REVIEW

**Comment by akasolace** [comment]
@wsbrenk I suggest we stick with my previous commit. I tested it and I think it works well. Can you split your PR and only push the one regarding Youth

**Comment by wsbrenk** [comment]
@akasolace i'm not sure if your change breaks the recalc feature. recalcSubskills calls model.calcSubskills too and needs the trainings between the downloads saved in the database, not the trainings of the current hoModel.

**Comment by wsbrenk** [comment]
var trainingWeeks = TrainingManager.getTrainings(previousDownload.getDate(), getNextTrainingDate) would do it. 

Proposed signature: getTrainings(fromDate, beforeDate) // beforeDate is used as exclusive date (next training is not included in the result)

**Comment by akasolace** [comment]
@wsbrenk I made a couple of tests again this morning, It seems to me that master is working well. Subskills are properly calculated and past and forward trainings are properly updated.... please let me know if you still see an issue that I missed ...

**Comment by wsbrenk** [comment]
Before Recalc:
beforerecalc

After Recalc (7 weeks)
afterRecalc

No trainingweeks are available for recalc loop as i mentioned above

**Comment by wsbrenk** [comment]
@akasolace i do not intend to use my pr. but you should introduce the method i proposed above. this should be used in calcSubskills instead of getRecentTrainings.

**Comment by akasolace** [comment]
@wsbrenk I don't really understand your request. I mean let say you want to recalculate subskill from `startDate`, you can already do something like: 

`var trainingWeeks = new TrainingWeekManager(startDate, false, true).getTrainingList()`

**Pull request closed without merging**
