### PR TITLE
Upgrade to darklaf 2.5.3

### PR DESCRIPTION
**Pull request by tychobrailleur**
Also cleanup by moving mouse listener creation in `addListeners`.

1. changes proposed in this pull request:
 
Upgrade darklaf to most recent version, and a bit of cleanup.
 
 
2. changelog and release_notes ...

 - [ ] have been updated
 - [x] do not require update

3. [Optional] suggested person to review this PR @akasolace

### CODE REVIEW

**Comment by akasolace** [comment]
Hello, you changed your mind ? Master was already on latest version of darklaf but what about the second part of your PR ?

**Comment by tychobrailleur** [comment]
I had forgotten to sync with upstream (somebody's a bit rusty...), it looks like it is no longer relevant...

**Comment by akasolace** [comment]
If you are up to it, there are couple of message on the forum regarding a bug on mac version. Apparently lot of users experience it: need to put CHPP code at each start of the application.

**Comment by tychobrailleur** [comment]
So the OAuth access token is not preserved or something?

**Comment by akasolace** [comment]
Yes it seems it is not stored. It only affect mac build so I can't test

> I am using HO 4.1 on the mac. My problem is that HO doesn't remember any settings inluding the CHPP-Code. Obviously the settings file is read only. What do I have to change?
Thanks in advance

>> Do you mean like every time you download info you need to give authorization?
If yes, I have same problem on Mac.

**Pull request closed without merging**
