### PR TITLE
Remove player state colours.

### PR DESCRIPTION
**Pull request by tychobrailleur**
As the state colours have now been removed, the multiline player label
    now displays details about their state: injured, suspended, two yellow
    cards, etc.  The single line labels do not display those icons.
    
    This commit was originally e96d911f8edeabfb6b4cf9b18db1541281ae769b,
    but it was reverted as it was causing an NPE because of a change for
    the groups icons.  This commit has been cherry-picked, with the
    exception of the change in question.

1. changes proposed in this pull request:
 
   - fixes issue #572 
 
2. changelog and release_notes ...

 - [x] have been updated
 - [ ] do not require update

3. [Optional] suggested person to review this PR @wsbrenk

### CODE REVIEW

**Comment by akasolace** [comment]
@wsbrenk do you think you can do this review ? If you have no time I can do it ... cheers

**Comment by wsbrenk** [comment]
checkout is done - i will start testing tomorrow

**Comment by akasolace** [comment]
Great thank you

**Comment by wsbrenk** [comment]
Yellow card icon missing in lineup for some players (here Mr Neuenfeld):

grafik

**Comment by tychobrailleur** [comment]
> i transfer listed one player and found an icon in lineup position, but there is no icon in player table below lineup and not in player overview panel. is that intended?

It is intended, only the multiline labels will get the icons, as there is very little space to put them on the single line one.  

> Yellow card icon missing in lineup (here Mr Neuenfeld) or is it intended to show only if there are two yellow cards?

There was no colour for a single yellow card, so I didn't add a corresponding icon.  I can add it if needs be?

**Comment by akasolace** [comment]
> > i transfer listed one player and found an icon in lineup position, but there is no icon in player table below lineup and not in player overview panel. is that intended?
> 
> It is intended, only the multiline labels will get the icons, as there is very little space to put them on the single line one.

I think @wsbrenk was refering to the status box ... plenty of room for icon there. Specialy next to the player name and everything else (injury, card, transfer listed, ...) goes into the status box.  @tychobrailleur could this be done ?

> 
> > Yellow card icon missing in lineup (here Mr Neuenfeld) or is it intended to show only if there are two yellow cards?
> 
> There was no colour for a single yellow card, so I didn't add a corresponding icon. I can add it if needs be?

@tychobrailleur yes I personnaly think it would be nice to also have the single yellow card ....

**Comment by tychobrailleur** [comment]
> I think @wsbrenk was refering to the status box ... plenty of room for icon there. Specialy next to the player name and everything else (injury, card, transfer listed, ...) goes into the status box. @tychobrailleur could this be done ?

I am not sure what you call the status box?  
From @wsbrenk's screenshot, the icon is there in the lineup position, but not in the table below, nor in the player overview table, which is intended.  Were you expecting to see the icon in another place?

Here is also my own screen (BTW, I am now getting those strange ratings for set pieces position, is this expected?): 
Screenshot from 2020-07-27 12-49-40



> @tychobrailleur yes I personnaly think it would be nice to also have the single yellow card ....

OK, sounds good!

**Comment by akasolace** [comment]
image

**Comment by akasolace** [comment]
> Here is also my own screen (BTW, I am now getting those strange ratings for set pieces position, is this expected?):

no, normaly the values are rounded before display ... this is also strange that only setpiece is affected ...

**Comment by tychobrailleur** [comment]
> @tychobrailleur this below is the status box I reffered to

Ah right, thanks!!  I haven't touched this at all, so is the suggestion to add the transferlisted icon to this column?

**Comment by akasolace** [comment]
>Ah right, thanks!! I haven't touched this at all, so is the suggestion to add the transferlisted icon to this column?

yes, I guess the idea is to have:
   - specialty icon next to the name  (done)
   - all status icons in status box   (missing transfer listed ...)
   - specialty + status icons in player check box  (missing single yellow card ...)
   - remove player colours to indicate status (done)

**Pull request merged**
