### PR TITLE
#1080 fix FutureTrainingManager.checkSkillChange rounding issue of sk…

### PR DESCRIPTION
**Pull request by wsbrenk**
…ill drops

1. changes proposed in this pull request:
 
   - fixes issue #1080
   
   - if not fixing an existing issue, comments explaining the purpose of the PR should be provided)
 
 
2. changelog and release_notes ...

 - [ ] have been updated
 - [ ] do not require update

3. [Optional] suggested person to review this PR @___

### CODE REVIEW

**Comment by akasolace** [comment]
instead of this what about my more general proposal, truncating values instead of rounding ? 
can't it help in other places in HO! ?

**Comment by wsbrenk** [comment]
@akasolace i didn't fount the place where i could replace rounding by truncating.

if truncation, then we need to find out whether the user is displaying one or two precision numbers and truncate accordingly.

**Comment by akasolace** [comment]
@wsbrenk If you agree this would be a more genral approach, I would close that PR and make a more general ticket...

**Comment by wsbrenk** [comment]
@akasolace i agree. display is suboptimal.

Concerning calculation i don't know if the current (alternative) formula tooks skills drops into account. if so - we overestimate the skill drops of trained skills. do you know who was responsible for that formula?

**Comment by akasolace** [comment]
> Concerning calculation i don't know if the current (alternative) formula tooks skills drops into account. if so - we overestimate the skill drops of trained skills. do you know who was responsible for that formula?

know sure I understand the question as I am not familiar with that part of the code. For me skill drops and training are separated formula as they do not occur at the same time, no ?

**Comment by wsbrenk** [comment]
> For me skill drops and training are separated formula as they do not occur at the same time, no ?

concerning hattrick you're right - but in HO the training calculation is done in one run at training date as far as i know. don't know if we could get the skill down date from chpp and whether  it is worth doing so.

**Pull request merged**
