### PR TITLE
future trainings marking

### PR DESCRIPTION
**Pull request by wsbrenk**
1. changes proposed in this pull request:
 
   - fixes issue #296   

uses maximum trainingsspeed instead of average for marking trainees.
   

3. [Optional] suggested person to review this PR @akasolace

### CODE REVIEW

**Comment by akasolace** [comment]
@wsbrenk thanks for the PR,  may I ask you to update both:

- https://github.com/akasolace/HO/blob/master/src/main/resources/changelog.md
- https://github.com/akasolace/HO/blob/master/src/main/resources/release_notes.md

thank you !

**Comment by wsbrenk** [comment]
@akasolace added on line to docs/release_notes(beta).md in my repo. is that also the source of the changelog.md? i added the same line to ...(dev).md. 
is that OK?

**Comment by akasolace** [comment]
@wsbrenk you should only update changelog.md and release_notes.md

**Comment by wsbrenk** [comment]
@akasolace sorry, now i found them in resources. should i revert the change of the previous commit?

**Comment by akasolace** [comment]
> @akasolace sorry, now i found them in resources. should i revert the change of the previous commit?

no thats fine, thank you

**Pull request merged**
