### PR TITLE
#1175 fix DBManager.instance init parentFolder

### PR DESCRIPTION
**Pull request by wsbrenk**
1. changes proposed in this pull request:
 
   - fixes issue #1175
   
   - if not fixing an existing issue, comments explaining the purpose of the PR should be provided)
 
 
2. changelog and release_notes ...

 - [ ] have been updated
 - [x] do not require update

3. [Optional] suggested person to review this PR @___

### CODE REVIEW

**Comment by akasolace** [comment]
I have doubt about this one. Dont know why this use have this issue but I dont see how this PR would fix it. 
We would need the exact logs.

**Comment by wsbrenk** [comment]
@akasolace workaround was to create the directory %APPDATA%/HO by hand. After that HO started.

**Comment by akasolace** [comment]
If the folder creation failed it should normally be reported in error logs, no? ...

**Comment by wsbrenk** [comment]
i'm not quiet sure - i only found 1 place that could create the parent db folder: HOLogger()  (line 43)

if this directory is not created by install4j, HO will only start if first some logs are written, before DBManager is called. Testing the write access in DbManager could not work on non existing parent folder.

**Comment by wsbrenk** [comment]
no idea if it really helps, but it shouldn't hurt either

**Pull request merged**
