### PR TITLE
#705 edit release channel config

### PR DESCRIPTION
**Pull request by wsbrenk**
1. changes proposed in this pull request:
 
   - fixes issue #705 
   
   - if not fixing an existing issue, comments explaining the purpose of the PR should be provided)
 
 
2. changelog and release_notes ...

 - [ ] have been updated
 - [x] do not require update

3. [Optional] suggested person to review this PR @akasolace

### CODE REVIEW

**Comment by akasolace** [comment]
@wsbrenk this will work indeed but it reopens #667

**Comment by wsbrenk** [comment]
> @wsbrenk this will work indeed but it reopens #667

@akasolace i would have thought that the commit https://github.com/akasolace/HO/commit/ef6fc65c6a62cc60a5b04f552683f18c2435289f would handle that, isn't it?

**Comment by akasolace** [comment]
> > @wsbrenk this will work indeed but it reopens #667
> 
> @akasolace i would have thought that the commit [ef6fc65](https://github.com/akasolace/HO/commit/ef6fc65c6a62cc60a5b04f552683f18c2435289f) would handle that, isn't it?

I am not sure this will have the intended effect ... I think it will change release channel of users during upgrade => which we do not want to do (if a user is on dev channel and upgraded to latest stable/beta he will still want to have his release channel on dev)

The bug #667 is only about new artefacts (all new artefacts, dev, beta or stable have release channel pointing to stable, whereas it should point to de version type).  I think the approach would be to have:
   -   a value bool releaseChannelSET = false, set as default in userparameter. 
   -   code setting release channel:
       - if releaseChannelSET  read from preference panel
       -  else allocated from version 

when the release channel is modified put     releaseChannelSET   = true

it is a bit the logic I had when I tried to clause #667 but I forgot the bool releaseChannel so effectively I was resetting the channel at each close.

@wsbrenk  not sure if all this is clear for you ... if you want to have a look please go ahae

**Comment by wsbrenk** [comment]
@akasolace as far as i understand, the update4000 method will work as desired if a user starts with a fresh installation of HO. Depending on the artefact the channel is initialized as required (i hope).

Only if the user is working with an existing database and release channel is set to any value, this value remains as it is. this could be an unintentional one, initialized by a wrong updateconf method of an old HO version. But i think we have no chance to destinguish if the given value was set intentional or not.

**Comment by akasolace** [comment]
I was under the impression that if the user start with fresh install release channel will always be setup to Stable (even for a beta or a dev build). For existing user going through updateDB400 it will réinitialise their release channel based on HO version (erasing their choice). I might be wrong though as you sound convinced this will work :-)

**Comment by wsbrenk** [comment]
@akasolace i think you're right. I should not state anything on saturday morning;-(

**Comment by akasolace** [comment]
😃

**Pull request merged**
