### PR TITLE
Add header for Alltid.

### LINKED ISSUE #942: [BUG] add header to hattid request
As requested by Harrid owner:

```
Header name: hattid-request-source
I will appreciate If you will put there "HO!" value for each request.
```

### PR DESCRIPTION
**Pull request by tychobrailleur**
This fixes #942.

1. changes proposed in this pull request:
 
Cf. above
 
2. changelog and release_notes ...

 - [ ] have been updated
 - [x] do not require update

3. [Optional] suggested person to review this PR @akasolace

### CODE REVIEW

**Comment by tychobrailleur** [comment]
@akasolace Are you able to test to see if everything still works ok for you?  Looks like Alltid doesn't quite work with my team.

**Comment by akasolace** [comment]
> @akasolace Are you able to test to see if everything still works ok for you? Looks like Alltid doesn't quite work with my team.

arf you are right ... nothing displayed

**Comment by akasolace** [comment]
pb is in HO ....  the endpoint is working 
https://hattid.com/api/leagueUnit/21641/teamHatstats?page=0&pageSize=8&sortBy=hatstats&sortDirection=asc&statType=max&season=76

**Comment by akasolace** [comment]
I open a ticket for this

**Comment by akasolace** [comment]
@tychobrailleur actually wanted to look at it now but it seems to work on master.  Latest dev release was not working though....

**Comment by tychobrailleur** [comment]
Ok, so all good?  Can alltid see the header being passed?

**Comment by akasolace** [comment]
Yes as far as I can tell HO! master is working well. Why I don't get is why the previous version not working. Could it be that hattid reject our queries if we don't pass the headers ? That could explain it and that I guess would also answer positively to your second question.

**Comment by akasolace** [comment]
@tychobrailleur actually I will need to test if it is not an issue installed version vs IDE (I mean working on IDE but not on installed version).  Looking at the log within HO! directory the installed version, I got:  
14:03:41 [Error]   module.series.promotion.HttpDataSubmitter: Error fetching data from Alltid for league team power ratings: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

**Comment by tychobrailleur** [comment]
> @tychobrailleur actually I will need to test if it is not an issue installed version vs IDE (I mean working on IDE but not on installed version). Looking at the log within HO! directory the installed version, I got:
> 14:03:41 [Error] module.series.promotion.HttpDataSubmitter: Error fetching data from Alltid for league team power ratings: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

This error occurs when OkHttp does not find the cert from the truststore, so it could be the jks file is not packaged properly with the released app.

I have refactored that part of the code to use TLS logic from okhttp to make it easier to follow, and I was hoping that `.addPlatformTrustedCertificates()` would have used the cacerts from the platform, but no joy -- although I checked GlobalSign R3 root CA was there... not sure why.  One for another day!

**Comment by akasolace** [comment]
yes I can't find any trustore.jks file on my computer outside of the code directory:
    - so I am curious why connection to anvil server is working ? 
    - I tried to copy the file to HO install directory but not joy, I am not sure where this file is supposed to be

**Comment by akasolace** [comment]
@tychobrailleur ok just fixed it .. this was indeed a packaging issue 
new artefact just released

**Comment by tychobrailleur** [comment]
Awesome, will test when I get the chance

**Pull request merged**
