### PR TITLE
update

### PR DESCRIPTION
**Pull request by mistermax80**

### CODE REVIEW

**Comment by akasolace** [comment]
there are conflict, 
you need first to rebase your local branch to the latest version of the master branch
and then make a pull request.

**Comment by akasolace** [comment]
your master branch should just follow origin/master ... you just do pull regularly 
then you create topic branch to do your work and when ready you make sure your master is sync with origin master, you rebase your branch to your master and then you open a pull request

**Comment by mistermax80** [comment]
I made pull but it show a conflict, and I triyng to update my master branc... I don't know it create this pull request. sorry... I'm training to use git... :(

**Comment by akasolace** [comment]
if the pull created a conflict it means you modified your local master which you should not. 
I suggest you save your work (in case you worked on master) then you reset your local master

```
$ git checkout master
# Reset master back to origin/master
$ git reset --hard origin/master
```

then you create a new feature branch out of master, you put back your changes and then you do the pull request,  remember never to work in master,  master should only track origin/master for you to have an up to date copy, and you work only on branch and you rebase regularly to avoid big conflict)

**Pull request closed without merging**
