### PR TITLE
copy db from old user directory to new directory on Linux

### PR DESCRIPTION
**Pull request by yaute74**
my proposal for #23

### CODE REVIEW

**Comment by akasolace** [comment]
Thank you for the fast PR,

what ennoys me is that, there are now few beta testers that are running the Linux version.
This commit would break there install:
1) either we consider this in the script (maybe overdone for only 10 beta testers
2) I just communicate about it to beta testers

It is late, I'll think about it tomorrow. Meanwhile, you are input are welcome

**Comment by yaute74** [comment]
For the backup you are right, it's better to do nothing. The user will be able to delete it after if he want.

For the ~/.local/ho it's not critical, it's just to be more standard. As we rename the home user, for the 435, I think it's the good time to do it. If users are annoyed by that leave it like that but it's a shame.

**Comment by akasolace** [comment]
@yaute74  ok then I propose to keep the installation folder in ~/.ho , it is really a details and it would avoid to mess up things with the beta testers (I see it has been downloaded 26 times already).

Concerning the first point, you want to leave it untouched or do you want to ask the question to user within the script?

Could you please amend you PR accordingly, I will then merge it. 
Thank you

**Comment by yaute74** [comment]
Personally I think the simples solution is the best: untouched

**Comment by akasolace** [comment]
thank you

**Pull request merged**
