### PR TITLE
Bug#422

### PR DESCRIPTION
**Pull request by wsbrenk**
1. changes proposed in this pull request:
 
   - fixes issue #422   
 
2. changelog and release_notes ...

 - [x] have been updated
 - [ ] do not require update

### CODE REVIEW

**Comment by akasolace** [comment]
thank you @wsbrenk, 1 remark and 1 question:
    - could you please rebase, this PR mixes things unrelated to this bug
    - was it only a bug in player analysis tab or was this function used somewhere else ?

Cheers

**Comment by wsbrenk** [comment]
@akasolace as far as i could see, the repaired function is only called by the player analysis panel

**Comment by wsbrenk** [comment]
@akasolace do you plan to pick this change to patch 2.x branch? Then i have to check if the changes would fit to this branch.

**Comment by wsbrenk** [comment]
@akasolace is this change ok for you or do you need one single commit?

**Comment by akasolace** [comment]
> @akasolace is this change ok for you or do you need one single commit?

@wsbrenk  perfect, thank you

> @akasolace do you plan to pick this change to patch 2.x branch? Then i have to check if the changes would fit to this branch.

tbh, I am wondering if next release won't be 3.0 directly ....

**Pull request merged**
