### PR TITLE
tentative closing #742

### PR DESCRIPTION
**Pull request by akasolace**
1. changes proposed in this pull request:
 
   - fixes issue #742
   
 
 
2. changelog and release_notes ...

 - [ ] have been updated
 - [x] do not require update

3. [Optional] suggested person to review this PR @___

### CODE REVIEW

**Comment by Synthespian** [comment]
No worries in switching to #777. 
Happy to test when ready (still shows as latest version today)

**Comment by Synthespian** [comment]
FYI ... downloaded HO-4.0.3308.2-portable-win-JRE.
Did a backup.
Made a new folder for 3308.
Copied in the 3x db folders
Copied in users.json

everything seems to be working.  So for any future "unable to upgrade in the application" that's all the files it seems it needs to bring over.

**Comment by akasolace** [comment]
@Synthespian yes this is the way to go for manual upgrade ..

**Comment by Synthespian** [comment]
I even brought over themes.  
I kinda asked but didn't get an answer of what I needed to switch so took that gamble (didn't spot in the forum :P)
As I said, I was the only person likely to be affected by this, but can confirm it looks like it's working.

Will go and repeat in HT.
Please close this now. :) 👍

**Pull request merged**
