### PR TITLE
Column 'Rating' removed from player and lineup tab

### PR DESCRIPTION
**Pull request by steffanots**
1. changes proposed in this pull request:
   #610
    
Since I added column LastMatchRating and now delete for display the Rating column, I have a problem with the configuration of the columns.
Are we doing a reset or are we going to update something?
Line code line 133 in UserColumnsTable will do job, but it not nice code.

### CODE REVIEW

**Comment by akasolace** [comment]
@tychobrailleur  considering @yaute74 absence lately, maybe you can review the PR and help @steffanots on this one. Apparently deleting the old columns is not that trivial => is that ok with you ? 
It is the continuation of #461 (see https://github.com/akasolace/HO/issues/461#issue-604312435)

**Comment by tychobrailleur** [comment]
I have added db update statements for this.

**Comment by akasolace** [comment]
@tychobrailleur you think this PR is ready for merge with the commits you made ?

**Comment by tychobrailleur** [comment]
> @tychobrailleur you think this PR is ready for merge with the commits you made ?

If you're happy with my changes (DbUpdater), then yes, good to go.

**Pull request merged**
